version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: library22A@
    volumes:
      - /extra/minio_data:/data
    command: server /data --console-address :9001

volumes:
  minio_data: